<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Craterboy.Core/Craterboy.Core.csproj" />
    <ProjectReference Include="../../src/Craterboy.Tester/Craterboy.Tester.csproj" />
  </ItemGroup>
  <Target Name="BuildSameBoyOracle" BeforeTargets="Build" Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <Exec Command="sh ../native/build-oracle.sh" />
    <ItemGroup>
      <OracleLibraries Include="../native/build/*.so" />
    </ItemGroup>
    <Copy SourceFiles="@(OracleLibraries)" DestinationFolder="$(OutDir)" />
  </Target>
</Project>
